USE  [PROBD2]
GO
----BORRA LAS TABLAS, SI ESTAS EXISTEN
DROP TABLE IF EXISTS ESTUDIANTES;

DROP TABLE IF EXISTS HISTORIAL;

DROP TABLE IF EXISTS CARRERA;

DROP TABLE IF EXISTS DOCENTE;

DROP TABLE IF EXISTS CURSO;

DROP TABLE IF EXISTS HABCURSO;

DROP TABLE IF EXISTS HORCURSO;

DROP TABLE IF EXISTS ASIGMATERIA;


