USE PROBD2
GO

ALTER PROC InsertEstudiante
	(@CARNET				AS BIGINT,
	@NOMBRE				AS VARCHAR(150),
	@APELLIDO			AS VARCHAR(150),
	@FECHANAC			AS DATE,
	@CORREO				AS VARCHAR(150),
	@TELEFONO			AS INT,
	@DIRECCION			AS VARCHAR(150),
	@DPI				AS BIGINT,
	@CARRERA			AS INT)
AS
BEGIN
	SET NOCOUNT ON;

		INSERT INTO dbo.ESTUDIANTES (CARNE,NOMBRE,APELLIDOS,FECHANAC,CORREO,TELEFONO,DIRECCION,DPI,CARRERA)
			VALUES
		       (@CARNET		,
		       @NOMBRE		, 
		       @APELLIDO	, 
		       @FECHANAC	, 
		       @CORREO		, 
		       @TELEFONO	, 
		       @DIRECCION	, 
		       @DPI			, 
		       @CARRERA	)
END
GO
